// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/*";
  };
  "./app/_components/protected-layout.tsx": {
    id: "app/_components/protected-layout";
    page: "/";
  };
  "./app/_components/app-sidebar-layout.tsx": {
    id: "app/_components/app-sidebar-layout";
    page: "/";
  };
  "./app/page.tsx": {
    id: "app/page";
    page: "/";
  };
  "./app/_components/non-login-layout.tsx": {
    id: "app/_components/non-login-layout";
    page: "/login";
  };
  "./app/login/page.tsx": {
    id: "app/login/page";
    page: "/login";
  };
  "./app/errors/not-found/page.tsx": {
    id: "app/errors/not-found/page";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "app/_components/protected-layout": typeof import("./src/./app/_components/protected-layout.tsx");
  "app/_components/app-sidebar-layout": typeof import("./src/./app/_components/app-sidebar-layout.tsx");
  "app/page": typeof import("./src/./app/page.tsx");
  "app/_components/non-login-layout": typeof import("./src/./app/_components/non-login-layout.tsx");
  "app/login/page": typeof import("./src/./app/login/page.tsx");
  "app/errors/not-found/page": typeof import("./src/./app/errors/not-found/page.tsx");
};