// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/users/create": {
    params: {};
  };
  "/users/:id": {
    params: {
      "id": string;
    };
  };
  "/users/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/requests": {
    params: {};
  };
  "/requests/create": {
    params: {};
  };
  "/requests/:id": {
    params: {
      "id": string;
    };
  };
  "/requests/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/audit-logs": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/users" | "/users/create" | "/users/:id" | "/users/:id/edit" | "/requests" | "/requests/create" | "/requests/:id" | "/requests/:id/edit" | "/audit-logs" | "/login" | "/*";
  };
  "./app/_components/layout/protected-layout.tsx": {
    id: "app/_components/layout/protected-layout";
    page: "/" | "/users" | "/users/create" | "/users/:id" | "/users/:id/edit" | "/requests" | "/requests/create" | "/requests/:id" | "/requests/:id/edit" | "/audit-logs";
  };
  "./app/_components/layout/app-sidebar-layout.tsx": {
    id: "app/_components/layout/app-sidebar-layout";
    page: "/" | "/users" | "/users/create" | "/users/:id" | "/users/:id/edit" | "/requests" | "/requests/create" | "/requests/:id" | "/requests/:id/edit" | "/audit-logs";
  };
  "./app/page.tsx": {
    id: "app/page";
    page: "/";
  };
  "./app/users/page.tsx": {
    id: "app/users/page";
    page: "/users";
  };
  "./app/users/create/page.tsx": {
    id: "app/users/create/page";
    page: "/users/create";
  };
  "./app/users/[id]/page.tsx": {
    id: "app/users/[id]/page";
    page: "/users/:id";
  };
  "./app/users/[id]/edit/page.tsx": {
    id: "app/users/[id]/edit/page";
    page: "/users/:id/edit";
  };
  "./app/requests/page.tsx": {
    id: "app/requests/page";
    page: "/requests";
  };
  "./app/requests/create/page.tsx": {
    id: "app/requests/create/page";
    page: "/requests/create";
  };
  "./app/requests/[id]/page.tsx": {
    id: "app/requests/[id]/page";
    page: "/requests/:id";
  };
  "./app/requests/[id]/edit/page.tsx": {
    id: "app/requests/[id]/edit/page";
    page: "/requests/:id/edit";
  };
  "./app/audit-logs/page.tsx": {
    id: "app/audit-logs/page";
    page: "/audit-logs";
  };
  "./app/_components/layout/non-login-layout.tsx": {
    id: "app/_components/layout/non-login-layout";
    page: "/login";
  };
  "./app/login/page.tsx": {
    id: "app/login/page";
    page: "/login";
  };
  "./app/errors/not-found/page.tsx": {
    id: "app/errors/not-found/page";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "app/_components/layout/protected-layout": typeof import("./src/./app/_components/layout/protected-layout.tsx");
  "app/_components/layout/app-sidebar-layout": typeof import("./src/./app/_components/layout/app-sidebar-layout.tsx");
  "app/page": typeof import("./src/./app/page.tsx");
  "app/users/page": typeof import("./src/./app/users/page.tsx");
  "app/users/create/page": typeof import("./src/./app/users/create/page.tsx");
  "app/users/[id]/page": typeof import("./src/./app/users/[id]/page.tsx");
  "app/users/[id]/edit/page": typeof import("./src/./app/users/[id]/edit/page.tsx");
  "app/requests/page": typeof import("./src/./app/requests/page.tsx");
  "app/requests/create/page": typeof import("./src/./app/requests/create/page.tsx");
  "app/requests/[id]/page": typeof import("./src/./app/requests/[id]/page.tsx");
  "app/requests/[id]/edit/page": typeof import("./src/./app/requests/[id]/edit/page.tsx");
  "app/audit-logs/page": typeof import("./src/./app/audit-logs/page.tsx");
  "app/_components/layout/non-login-layout": typeof import("./src/./app/_components/layout/non-login-layout.tsx");
  "app/login/page": typeof import("./src/./app/login/page.tsx");
  "app/errors/not-found/page": typeof import("./src/./app/errors/not-found/page.tsx");
};